# Generated by Django 4.0.3 on 2022-03-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_country_continent_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
    ]
