# Generated by Django 4.0.3 on 2022-03-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price_for_adult',
            field=models.FloatField(blank=True, default='not mentioned by owner', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_for_child',
            field=models.FloatField(blank=True, default='not mentioned by owner', null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='promoted',
            field=models.IntegerField(blank=True, default='not mentioned by owner', null=True),
        ),
    ]
